version: 2

sources:
  - name: MARS_BRONZE
    description: "Bronze layer tables containing raw data returned from NASA APIs, preserving original JSON structure."
    database: MARS_DB
    schema: MARS_BRONZE
    tables:
      - name: RAW_PHOTO_RESPONSE
        description: "Batched responses from NASA Mars Rover Photos API. Contains image metadata and URLs for timelapse video creation and analytics."
        columns:
          - name: PHOTOS
            description: "JSON array of photo responses from the Mars Rover Photos API endpoint."
            tests:
              - not_null
      - name: RAW_COORDINATE_RESPONSE
        description: "Coordinate tracking data from NASA MMGIS for Perseverance and Curiosity rovers. Each response contains a rover's complete mission traversal path."
        columns: 
          - name: COORDINATES
            description: "JSON array of coordinate responses from NASA MMGIS path tracking endpoints."
            tests:
              - not_null
      - name: RAW_MANIFEST_RESPONSE
        description: "Mission manifest responses from NASA Mars Rover Manifest API. Contains high-level mission statistics and metadata for each rover."
        columns:
        - name: MANIFESTS
          description: "JSON array of mission manifest responses from the Mars Rover Manifest API endpoint."
          tests:
            - not_null
  - name: MARS_SILVER
    description: "Silver layer views and incremental tables containing cleaned, normalized, and flattened data from Bronze schema tables."
    database: MARS_DB
    schema: MARS_SILVER
    tables:
      - name: FLAT_PHOTO_RESPONSE
        description: "Incremental table containing flattened photo data from RAW_PHOTO_RESPONSE with individual photo records."
        columns:
          - name: IMAGE_ID
            description: "Unique identifier for each photo taken by Mars rovers."
            tests:
              - not_null
              - unique
      - name: FLAT_COORDINATE_RESPONSE
        description: "Incremental table containing flattened coordinate data from RAW_COORDINATE_RESPONSE with individual path segments."
        columns:
          - name: ROVER_NAME
            description: "Name of the Mars rover that traveled the coordinate path."
            tests:
              - not_null
          - name: SOL
            description: "Sol (Mars day) when the coordinate path was traveled."
            tests:
              - not_null
      - name: FLAT_MANIFEST_RESPONSE
        description: "Incremental table containing flattened manifest data from RAW_MANIFEST_RESPONSE with rover mission summaries."
        columns:
          - name: ROVER_NAME
            description: "Name of the Mars rover for mission manifest data."
            tests:
              - not_null
              - unique
      - name: FACT_PHOTOS
        description: "Fact table view containing normalized photo data with foreign key relationships to dimension tables."
        columns:
          - name: IMAGE_ID
            description: "Unique identifier for each photo (primary key)."
            tests:
              - not_null
              - unique
      - name: FACT_PATH
        description: "Fact table view containing rover traversal path data with movement segments and distance calculations."
        columns:
          - name: SOL
            description: "Unique identifier for each path segment (primary key)."
            tests:
              - not_null
              - unique
      - name: DIM_ROVERS
        description: "Dimension table view containing Mars rover attributes and mission metadata."
        columns:
          - name: ROVER_ID
            description: "Unique identifier for each Mars rover (primary key)."
            tests:
              - not_null
              - unique
      - name: DIM_CAMERAS
        description: "Dimension table view containing camera specifications and categorizations for all rover instruments."
        columns:
          - name: CAMERA_ID
            description: "Unique identifier for each camera instrument (primary key)."
            tests:
              - not_null
              - unique
      - name: DIM_COORDINATE
        description: "Dimension table view containing coordinate reference data and location metadata."
        columns:
          - name: COORDINATE_ID
            description: "Unique identifier for each coordinate point. Composite key of rover_id, sol, and sequence number."
            tests:
              - not_null
              - unique
      - name: VALIDATION_PHOTO_GAPS
        description: "Data quality view identifying discrepancies between manifest data and actual photo records at the sol level."
        columns:
        - name: ROVER_NAME
          description: "Name of the Mars rover being validated for data gaps."
          tests:
            - not_null
  - name: MARS_GOLD
    description: "Gold layer incremental tables containing analysis-ready datasets from joined silver views."
    database: MARS_DB
    schema: MARS_GOLD
    tables:
      - name: PHOTO_SUMMARY
        description: "Breakdown of the number of photos taken and number of cameras used by sol. Used in validation_photo_gaps to compare with manifest data."
      - name: DAILY_ACTIVITY
        description: "Breakdown of rover travel distance and the number of photos taken each day"
      - name: CAMERA_TRAVEL_CORRELATION
        description: "Correlation between camera usage and travel distance"

models:
  - name: FLAT_PHOTO_RESPONSE
    description: "Incremental table containing flattened photo data from RAW_PHOTO_RESPONSE with individual photo records and metadata."
    columns:
      - name: IMAGE_ID
        description: "Unique identifier for each photo taken by Mars rovers (primary key)."
        tests:
          - not_null
          - unique
      - name: ROVER_NAME
        description: "Name of the Mars rover that captured the photo."
        tests:
          - not_null
          - accepted_values:
              values: ['Perseverance', 'Curiosity', 'Opportunity', 'Spirit']
      - name: SOL
        description: "Sol (Mars day) when the photo was captured, starting from rover landing day."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: EARTH_DATE
        description: "Corresponding Earth date when the photo was captured."
        tests:
          - not_null
      - name: IMG_SRC
        description: "Direct HTTP URL link to the full-resolution image file."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "LIKE 'http%'"
      - name: CAMERA_NAME
        description: "Abbreviated name of the camera instrument that captured the photo."
        tests:
          - not_null
  - name: FLAT_COORDINATE_RESPONSE
    description: "Incremental table containing flattened coordinate data from RAW_COORDINATE_RESPONSE with rover traversal path segments."
    columns:
      - name: ROVER_NAME
        description: "Name of the Mars rover that traveled the coordinate path segment."
        tests:
          - not_null
          - accepted_values:
              values: ['Perseverance', 'Curiosity', 'Opportunity', 'Spirit']
      - name: SOL
        description: "Sol (Mars day) when the rover traveled this coordinate path segment."
        tests:
          - not_null
      - name: TO_RMC
        description: "Ending reference point coordinate for the traversal path segment."
        tests:
          - not_null
      - name: FROM_RMC
        description: "Starting reference point coordinate for the traversal path segment."
        tests:
          - not_null
      - name: SCLK_END
        description: "Spacecraft clock ending timestamp for the path traversal segment."
        tests:
          - not_null
      - name: SCLK_START
        description: "Spacecraft clock starting timestamp for the path traversal segment."
        tests:
          - not_null
      - name: LENGTH
        description: "Distance traveled in meters for this path segment."
        tests:
          - not_null
  - name: FLAT_MANIFEST_RESPONSE
    description: "Incremental table containing flattened manifest data from RAW_MANIFEST_RESPONSE with rover mission summary statistics."
    columns:
      - name: ROVER_NAME
        description: "Name of the Mars rover for mission manifest data."
        tests:
          - not_null
          - unique
      - name: STATUS
        description: "Current mission status of the rover: 'active' for ongoing missions or 'complete' for concluded missions."
        tests:
          - not_null
      - name: MAX_SOL
        description: "Highest sol (Mars day) number reached by the rover in its mission."
        tests:
          - not_null
      - name: MAX_DATE
        description: "Most recent Earth date of rover activity and data collection."
        tests:
          - not_null
      - name: TOTAL_PHOTOS
        description: "Total count of photos captured by the rover throughout its entire mission."
        tests:
          - not_null
      - name: LAUNCH_DATE
        description: "Earth date when the rover mission was launched from Earth."
        tests:
          - not_null
      - name: LANDING_DATE
        description: "Earth date when the rover successfully landed on Mars surface."
        tests:
          - not_null
      - name: PHOTOS
        description: "Nested JSON data containing detailed photo count statistics for each individual sol of the rover mission."
        tests:
          - not_null
        
